name: update-readme

on:
  # Run on updates to main
  push:
    branches:
      - main

  # Run daily at midnight
  schedule:
    - cron: '0 0 * * *'

  # Allow option to run manually
  workflow_dispatch:

jobs:
  update-readme:
    name: Build and Deploy Dynamic README
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      # Checkout and fetch the current repository with one previous commit
      - name: Check out repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      # Set up Go
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: '1.20'

      # Cache Go modules for faster builds
      - name: Cache Go modules
        uses: actions/cache@v3
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: ${{ runner.os }}-go-

      # Build the README
      - name: Build README
        run: |
          cd ${GITHUB_WORKSPACE}/.update
          go mod tidy
          go run main.go

      # Check if the newly generated README actually changed
      - name: Check for changes
        id: git_diff
        run: |
          git add --all
          if git diff-index --quiet HEAD; then
            echo "no_changes=true" >> $GITHUB_OUTPUT
          else
            echo "no_changes=false" >> $GITHUB_OUTPUT
          fi

      # Commit and push changes if there are any
      - name: Commit and push changes
        if: steps.git_diff.outputs.no_changes == 'false'
        run: |
          git config user.name "${{ GITHUB.ACTOR }}"
          git config user.email "${{ GITHUB.ACTOR }}@users.noreply.github.com"

          git commit -m "auto: update dynamic content (README)"
          git push -f "https://${{ secrets.GITHUB_TOKEN }}@github.com/${{ GITHUB.REPOSITORY }}.git" HEAD:main

      # Notify if no changes were detected
      - name: Notify No Changes
        if: steps.git_diff.outputs.no_changes == 'true'
        run: echo "No changes detected in README, skipping commit"